name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan

  test:
    needs: lint
    strategy:
      matrix:
        include:
          - ckan-version: "master"
            ckan-image: "ckan/ckan-dev:master-py3.10"
          - ckan-version: "2.11"
            ckan-image: "ckan/ckan-dev:2.11-py3.10"
          - ckan-version: "2.10"
            ckan-image: "ckan/ckan-dev:2.10-py3.10"
          - ckan-version: "2.9"
            ckan-image: "ckan/ckan-dev:2.9-py3.9"
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.ckan-image }}
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}-solr9
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
      redis:
          image: redis:alpine
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      # required for CKAN 2.10 (if datastore is enabled)
      CKAN__DATAPUSHER__API_TOKEN: XX

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements (common)
      run: |
        pip install -e .
        pip install -r dev-requirements.txt
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
    - name: Setup extension (CKAN >= 2.9)
      run: |
        ckan -c test.ini db init
        # Disable datastore plugin as it messes with the tests
        export CKAN__PLUGINS=envvars
        ckan config-tool /srv/app/src/ckan/test-core.ini "ckan.plugins=envvars"
    - name: Run tests
      run: |
        pytest -v --ckan-ini=test.ini \
           --cov=ckanext.envvars \
           --cov-report=xml \
           --cov-append \
           --disable-warnings \
           ckanext/envvars/tests/
